-- Haribo Sketch v9
-- Supabase → SQL Editor → New query 에 전부 붙여넣고 RUN
-- v7/v8 SQL을 실행했어도 이 SQL을 그대로 다시 실행하면 됩니다.

create table if not exists public.rooms (
  room_id text primary key,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.strokes (
  id bigint generated by default as identity primary key,
  room_id text not null references public.rooms(room_id) on delete cascade,
  client_id text,
  layer_no integer not null default 1,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.strokes
add column if not exists client_id text;

alter table public.strokes
add column if not exists layer_no integer not null default 1;

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  room_id text not null references public.rooms(room_id) on delete cascade,
  client_id text,
  nickname text not null,
  message text not null check (char_length(message) <= 200),
  created_at timestamptz not null default now()
);

create index if not exists strokes_room_id_id_idx
on public.strokes(room_id, id);

create index if not exists strokes_room_client_idx
on public.strokes(room_id, client_id);

create index if not exists chat_room_id_id_idx
on public.chat_messages(room_id, id);

alter table public.rooms enable row level security;
alter table public.strokes enable row level security;
alter table public.chat_messages enable row level security;

drop policy if exists "rooms public select" on public.rooms;
drop policy if exists "rooms public insert" on public.rooms;
drop policy if exists "rooms public update" on public.rooms;
drop policy if exists "rooms public delete" on public.rooms;

create policy "rooms public select"
on public.rooms for select
to anon, authenticated
using (true);

create policy "rooms public insert"
on public.rooms for insert
to anon, authenticated
with check (true);

create policy "rooms public update"
on public.rooms for update
to anon, authenticated
using (true)
with check (true);

create policy "rooms public delete"
on public.rooms for delete
to anon, authenticated
using (true);

drop policy if exists "strokes public select" on public.strokes;
drop policy if exists "strokes public insert" on public.strokes;
drop policy if exists "strokes public delete" on public.strokes;

create policy "strokes public select"
on public.strokes for select
to anon, authenticated
using (true);

create policy "strokes public insert"
on public.strokes for insert
to anon, authenticated
with check (layer_no between 1 and 3);

create policy "strokes public delete"
on public.strokes for delete
to anon, authenticated
using (true);

drop policy if exists "chat public select" on public.chat_messages;
drop policy if exists "chat public insert" on public.chat_messages;
drop policy if exists "chat public delete" on public.chat_messages;

create policy "chat public select"
on public.chat_messages for select
to anon, authenticated
using (true);

create policy "chat public insert"
on public.chat_messages for insert
to anon, authenticated
with check (char_length(message) between 1 and 200);

create policy "chat public delete"
on public.chat_messages for delete
to anon, authenticated
using (true);
